<?php
$title = 'My Blog\'s post';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
  <a href="<?php echo $this->url('blog-post', array('action' => 'index')); ?>">Back to Blog</a>
</p>

<div class="blogpost-outer"><div class="blogpost">
        
<?php
  
//var_dump($user);
//var_dump($user->email);
//echo 'NAME??? '. $this->get_zfcuser_by_id_helper($post->user_id, $user);

?>
        
        
<?php if($this->zfcUserIdentity() && $post->user_id == $this->zfcUserIdentity()->getId()): ?>
<p>
  <span><a href="<?php echo $this->url('blog-post', array('action' => 'edit', 'id' => $post->id)); ?>">Edit</a></span>
  <span><a href="<?php echo $this->url('blog-post', array('action' => 'delete', 'id' => $post->id)); ?>">Delete</a></span>
</p>
<?php endif; ?>
<p><small class=""><?php echo 'Written by ' . $this->escapeHtml($this->get_zfcuser_by_id_helper($post->user_id, $user)); ?></small></p>
<p>
    <small class="small"><?php echo 'Created on ' . $this->escapeHtml($this->date_format_helper($post->created,'d-m-Y H:i')); ?></small>
<?php if (isset($post->updated) && !empty($post->updated)): ?>
    <br /><small class="small"><?php echo 'Updated on ' . $this->escapeHtml(date('d-m-Y H:i',strtotime( $post->updated ))); ?></small>
<?php endif; ?>
<h2><?php echo $this->escapeHtml($post->title); ?></h2>
<p><?php echo $this->escapeHtml($post->intro); ?></p>
<p><?php echo $this->escapeHtml($post->fulltext); ?></p>
</div></div>